* Memo
**  [2023-01-02 Mon 14:36] 
aaaa
**  [2023-01-03 火 11:24] 
*** org-modeでGoalの項目を作る
*** org-modeでDoingの項目を作る
**  [2023-01-04 水 23:56] 
*** Emacs LispをScrach bufferで実行してみる。
*** 便利そうなEl-getを使ってみる
*** リスト遊びを一通り読んでみる。感想を書く。
*** PowerShell製メモアプリをGithubに上げる。
*** シェル・ワンライナーを一日一問解く
*** Org-modeで習慣付ける方法
**** Org-habits
*** カメラでつむちゃん動くときは、ｓモード（シャッター優先）にして撮るとスマホで撮れない写真が撮れる
**  [2023-01-05 Thu 14:06] 
*** 
*** 
**  [2023-02-14 Tue 21:46] 
**  [2023-02-15 Wed 22:19] 
**  [2023-03-01 Wed 07:47] 
今日は何日
このキーボードいい感じ
めちゃサクサク動く、軽い
イェー
早くお風呂に入らないと
早く会社に行かないと
**  [2023-09-16 Sat 01:06]
**  [2023-11-03 Fri 22:07] 
**  [2023-12-07 Thu 14:09] 
**  [2023-12-18 Mon 09:30] 
- 技術開発課での工夫
  - 同僚の仕事を得意のプログラミングで改善した。
  - 流体解析の仕事
- 自己PR
  得意のプログラミングで従来の仕事を効率化して、
** 志望理由
志望理由は主に二点あります。
私はLinuxやシェルスクリプトなどプログラミングについて自主的に勉強しており、更にスキルアップできる環境を求めていること
OSSの普及に興味があり、貴社のLinux/OSSのサポートの技術支援業務であれば、よりOSS普及に貢献できること
この二つが志望理由になります。
1つ目について、私は自動車の排気系の会社で排気音や排気ガスの流れシミュレーションを担当していました。
しかし、前職場でのシミュレーション業務よりも、業務効率改善に用いたプログラミングのスキルを上げたいと思うようになりました。
また自己研鑽で、Linuxやシェルスクリプトの勉強をしてましたが、職場のセキュリティの都合で活用できる知識は限られてました。
以上のことから、自分のLinux知識やプログラミングスキルを更に高められるポジションに移りたいと考えるようになりました。
2つ目について、プログラミングを始めとするOSSの活用が一般企業では普及していないと感じており、OSS普及のためのサポートエンジニアになりたいと思いました。
企業がOSS活用できない理由として、セキュリティの問題とOSS活用のスキル不足があると思います。
貴社のLinux/OSS事業はその2つをサポートできると考えており、またOSS普及に貢献できると考えます。
以上の2点が、私の志望動機になります。
